# Load variables
- include_vars: local.yml
  tags: always

- name: user → copy zsh config
  tags: dotfiles, zsh
  ansible.builtin.copy:
    src: /.zshrc
    dest: "{{ user_dir }}/.zshrc"
    owner: vscode
    mode: 0600
    force: yes
