# Load variables
- include_vars: local.yml
  tags: always

- name: Use zsh as default shell
  blockinfile:
    path: "{{ user_dir }}/.bashrc"
    block: |
      if command -v zsh >/dev/null; then
        exec zsh -l
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ZSH DEFAULT SHELL"
    create: yes

- name: user → copy zsh config
  tags: dotfiles, zsh
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ user_dir }}/.zshrc"
    owner: vscode
    mode: 0600
    force: yes
