# Load variables
- include_vars: local.yml
  tags: always

- name: Use zsh as default shell
  blockinfile:
    path: "{{ user_dir }}/.bashrc"
    block: |
      if command -v zsh >/dev/null; then
        exec zsh -l
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ZSH DEFAULT SHELL"
    create: yes

- name: user → copy zsh config
  tags: dotfiles, zsh
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ user_dir }}/.zshrc"
    owner: vscode
    mode: 0600
    force: yes

- name: Check if Homebrew is installed
  command: brew --version
  register: brew_check
  failed_when: false

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_check.rc != 0

- name: Install packages with Homebrew
  homebrew:
    name:
      - bat
      - jq
      - starship
    state: present
    path: "/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
