# Load variables
- include_vars: local.yml
  tags: always

- block:
    # Make sure users exist on the system
    - import_tasks: users/sillypoise.yml
    - import_tasks: software/packages_development.yml
    - import_tasks: software/packages_utilities.yml
- name: user → copy zsh config
  tags: dotfiles, zsh
  ansible.builtin.copy:
    src: /.zshrc
    dest: "{{ user_dir }}/.zshrc"
    owner: sillypoise
    mode: 0600
    force: yes
